name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          # SHOW_LANGUAGE: "False"
          # SHOW_OS: "False"
          SHOW_TIMEZONE: "False"
          # SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_TIMELINE: "False"
          # IGNORED_REPOS: "waka-readme-stats, my-first-repo"
          # SYMBOL_VERSION: 1
          DEBUG_LOGGING: "False"
          # LOCALE: "en"  # Atur sesuai locale kamu (contoh: "id" untuk Bahasa Indonesia)
          # SECTION_NAME: "waka"
          # COMMIT_BY_ME: "False"
          # COMMIT_MESSAGE: "Updated with Dev Metrics"
          # COMMIT_USERNAME: "readme-bot"
          # COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
