name: Waka Readme

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 0/6 * * *"
  workflow_dispatch:
  push: { branches: ["main", "master"] }
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
